#!/usr/bin/env ruby


THEME_NAME = 'graydot'


## 16x16
actions_16x16 = {
  '._file_add' => [
    'add',
    'gtk-add',
    'list-add',
  ],

  '._file_remove' => [
    'gtk-remove',
    'list-remove',
    'remove',
  ],

  '._file_new' => [
    'document-new',
    'filenew',
    'gtk-new',
    'stock_new-text',
  ],

  '._file_properties' => [
    'document-properties',
    'gtk-properties',
    'stock_file-properites',
    'stock_properties',
  ],

  '._file_save' => [
    'document-save',
    'filesave',
    'gtk-save',
    'stock_save',
  ],

  '._file_save_as' => [
    'document-save-as',
    'filesaveas',
    'gtk-save-as',
    'stock_save-as',
  ],

  '._file_open' => [
    'document-open',
    'fileopen',
    'gtk-open',
  ],

  '._file_reload' => [
    'gtk-refresh',
    'reload',
    'reload3',
    'reload_all_tabs',
    'reload_page',
    'stock_refresh',
    'view-refresh',
  ],

  '._file_stop' => [
    'gtk-cancel',
    'gtk-stop',
    'process-stop',
    'stock_stop',
    'stop',
  ],

  '._file_close' => [
    'gtk-close',
    'stock_close',
    'window-close',
  ],

  '._file_exit' => [
    'application-exit',
    'exit',
    'gtk-quit',
    'xfce-system-exit',
  ],

  '._edit_edit' => [
    'gtk-edit',
  ],

  '._edit_find' => [
    'edit-find-replace',
    'edit-find',
    'filefind',
    'find',
    'gnome-searchtool',
    'gtk-find-and-replace',
    'gtk-find',
    'kfind',
    'search',
    'stock_search-and-replace',
    'stock_search',
    'system-search',
  ],

  '._edit_select_all' => [
    'edit-select-all',
    'gtk-select-all',
    'stock_select-all',
  ],

  '._edit_copy' => [
    'edit-copy',
    'editcopy',
    'gtk-copy',
    'stock_copy',
  ],

  '._edit_cut' => [
    'edit-cut',
    'editcut',
    'gtk-cut',
    'stock_cut',
  ],

  '._edit_paste' => [
    'edit-paste',
    'editpaste',
    'gtk-paste',
    'stock_paste',
  ],

  '._edit_clear' => [
    'edit-clear',
    'editclear',
    'gtk-clear',
  ],

  '._edit_delete' => [
    'edit-delete',
    'editdelete',
    'gtk-delete',
    'stock_delete',
  ],

  '._edit_undo' => [
    'edit-redo-rtl',
    'edit-undo',
    'gtk-undo-ltr',
    'stock_undo',
    'undo',
  ],

  '._edit_redo' => [
    'edit-redo',
    'edit-undo-rtl',
    'gtk-redo-ltr',
    'redo',
    'stock_redo',
  ],

  '._edit_sort_ascending' => [
    'gtk-sort-ascending',
    'view-sort-ascending',
  ],

  '._edit_sort_descending' => [
    'gtk-sort-descending',
    'view-sort-descending',
  ],

  '._go_up' => [
    'go-up',
    'gtk-go-up',
    'stock_up',
    'up',
  ],

  '._go_down' => [
    'down',
    'go-down',
    'gtk-go-down',
    'stock_down',
  ],

  '._go_left' => [
    'back',
    'go-previous',
    'gtk-go-back-ltr',
    'gtk-go-forward-rtl',
    'previous',
    'stock_left',
  ],

  '._go_right' => [
    'forward',
    'go-next',
    'gtk-go-back-rtl',
    'gtk-go-forward-ltr',
    'next',
    'stock_right',
  ],

  '._go_top' => [
    'go-top',
    'gtk-goto-top',
    'stock_top',
    'top',
  ],

  '._go_bottom' => [
    'bottom',
    'go-bottom',
    'gtk-goto-bottom',
    'stock_bottom',
  ],

  '._go_first' => [
    'go-first',
    'go-last-rtl',
    'gtk-goto-first-ltr',
    'gtk-goto-last-rtl',
    'start',
    'stock_first',
  ],

  '._go_last' => [
    'finish',
    'go-first-rtl',
    'go-last',
    'gtk-goto-first-rtl',
    'gtk-goto-last-ltr',
    'stock_last',
  ],

  '._go_jump' => [
    'go-jump',
    'gtk-jump-to-ltr',
    'gtk-jump-to-rtl',
  ],

  '._go_home' => [
    'go-home',
    'gohome',
    'gtk-home',
    'kfm_home',
    'redhat-home',
    'stock_home',
  ],

  '._media_play' => [
    'gtk-media-play-ltr',
    'media-playback-start',
    'player_play',
    'stock_media-play',
  ],

  '._media_next' => [
    'gtk-media-next-ltr',
    'gtk-media-previous-rtl',
    'media-skip-forward',
    'player_end',
    'stock_media-next',
  ],

  '._media_previous' => [
    'gtk-media-next-rtl',
    'gtk-media-previous-ltr',
    'media-skip-backward',
    'player_start',
    'stock_media-prev',
  ],

  '._media_pause' => [
    'gtk-media-pause',
    'media-playback-pause',
    'player_pause',
    'stock_media-pause',
  ],

  '._media_stop' => [
    'gtk-media-stop',
    'media-playback-stop',
    'player_stop',
    'stock_media-stop',
  ],

  '._view_fullscreen' => [
    'gtk-fullscreen',
    'stock_fullscreen',
    'view-fullscreen',
    'window_fullscreen',
  ],

  '._view_nofullscreen' => [
    'gtk-leave-fullscreen',
    'stock_leave-fullscreen',
    'view-restore',
    'window_nofullscreen',
  ],

  '._view_zoom_in' => [
    'gtk-zoom-in',
    'stock_zoom-in',
    'viewmag+',
    'zoom-in',
  ],

  '._view_zoom_out' => [
    'gtk-zoom-out',
    'stock_zoom-out',
    'viewmag-',
    'zoom-out',
  ],

  '._view_zoom_original' => [
    'gtk-zoom-100',
    'stock_zoom-1',
    'viewmag1',
    'zoom-original',
  ],

  '._view_zoom_fit' => [
    'gtk-zoom-fit',
    'stock_zoom-page',
    'viewmagfit',
    'zoom-best-fit',
    'zoom-fit-best',
  ],

  '._etc_help' => [
    'gtk-help',
    'help-contents',
    'help',
    'stock_help',
  ],

  '._etc_help_about' => [
    'gtk-about',
    'help-about',
    'stock_about',
  ],

  '._etc_run' => [
    'gnome-run',
    'gtk-execute',
    'system-run',
  ],
}


apps_16x16 = {
  '._help' => [
    'gnome-help',
    'help-browser',
    'khelpcenter',
    'susehelpcenter',
  ],

  '._text_editor' => [
    'accessories-text-editor',
    'kedit',
    'text-editor',
  ],
}


categories_16x16 = {
  '._control_center' => [
    'gnome-control-center',
    'gnome-settings',
    'gtk-preferences',
    'kcontrol',
    'preferences-desktop',
    'redhat-preferences',
    'xfce4-settings',
  ],
}


devices_16x16 = {
  '._hard_disk' => [
    'drive-harddisk',
    'gnome-dev-harddisk-1394',
    'gnome-dev-harddisk-usb',
    'gnome-dev-harddisk',
    'gtk-harddisk',
    'harddrive',
    'hdd_unmount',
    'yast_HD',
    'yast_idetude',
  ],

  '._optical_disc' => [
    'cdrom_unmount',
    'cdwriter_unmount',
    'dvd_unmount',
    'gnome-dev-cdrom-audio',
    'gnome-dev-disc-cdr',
    'gnome-dev-disc-cdrw',
    'gnome-dev-disc-dvdr-plus',
    'gnome-dev-disc-dvdr',
    'gnome-dev-disc-dvdram',
    'gnome-dev-disc-dvdrom',
    'gnome-dev-disc-dvdrw',
    'gtk-cdrom',
    'media-cdrom',
    'media-optical',
  ],
}


mimetypes_16x16 = {
  '._file_app' => [
    'application-x-executable',
    'binary',
    'exec',
    'gnome-fs-executable',
    'gnome-mime-application-x-executable',
    'gnome-mime-application-x-ms-dos-executable',
  ],

  '._file_blender' => [
    'application-x-blender',
  ],

  '._file_database' => [
    'application-x-sqlite3',
  ],

  '._file_key' => [
    'application-x-pem-key',
  ],

  '._file_key_pub' => [
    '',
  ],

  '._file_torrent' => [
    'application-x-bittorrent',
  ],

  '._file_disc_image' => [
    'application-x-cd-image',
  ],

  '._script' => [
    'application-x-ruby',
    'gnome-mime-application-x-perl',
    'gnome-mime-application-x-python-bytecode',
    'gnome-mime-application-x-shellscript',
    'gnome-mime-text-x-csh',
    'gnome-mime-text-x-python',
    'gnome-mime-text-x-sh',
    'gnome-mime-text-x-zsh',
    'shellscript',
    'stock_script',
    'text-x-python3',
    'text-x-script',
  ],

  '._doc_txt' => [
    'ascii',
    'empty',
    'gnome-mime-text',
    'mime_ascii',
    'misc',
    'package_editors',
    'template_source',
    'text-x-generic-template',
    'text-x-generic',
    'txt',
    'unknown',
  ],

  '._doc_pdf' => [
    'application-pdf',
    'application-x-pdf',
    'gnome-mime-application-pdf',
  ],

  '._doc_djvu' => [
    'image-vnd.djvu',
  ],

  '._doc_odt' => [
    'application-vnd.oasis.opendocument.text',
  ],

  '._doc_ods' => [
    'application-vnd.oasis.opendocument.spreadsheet',
  ],

  '._doc_doc' => [
    'application-msword',
    'application-vnd.openxmlformats-officedocument.wordprocessingml.document',
  ],

  '._doc_xls' => [
    'application-vnd.ms-excel',
    'application-vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ],

  '._doc_html' => [
    'text-html',
  ],

  '._doc_epub' => [
    'application-epub+zip',
  ],

  '._doc_fb2' => [
    'application-x-fictionbook+xml',
  ],

  '._image' => [
    'gnome-mime-image',
    'image-x-generic',
    'image',
  ],

  '._image_jpg' => [
    'image-jpeg',
  ],

  '._image_png' => [
    'image-png',
  ],

  '._image_svg' => [
    'image-svg+xml',
  ],

  '._audio' => [
    'audio-x-generic',
    'gnome-mime-audio',
    'sound',
  ],

  '._video' => [
    'gnome-mime-video',
    'video-x-generic',
    'video',
  ],

  '._pkg' => [
    'application-x-compressed-tar',
    'application-x-tar',
    'application-zip',
    'gnome-mime-application-x-archive',
    'gnome-mime-application-x-bzip-compressed-tar',
    'gnome-mime-application-x-bzip',
    'gnome-mime-application-x-compress',
    'gnome-mime-application-x-rar',
    'gnome-mime-application-zip',
    'gnome-package',
    'package-x-generic',
    'package',
    'zip',
    'application-x-7z-compressed',
  ],

  '._pkg_apk' => [
    'application-vnd.android.package-archive',
  ],

  '._pkg_encrypted' => [
    'application-pgp-encrypted',
  ],

  '._pkg_rar' => [
    'application-vnd.rar',
  ],
}


places_16x16 = {
  '._folder' => [
    'folder',
    'gnome-fs-directory',
    'gtk-directory',
    'inode-directory',
    'stock_folder',
  ],

  '._folder_home' => [
    'folder_home',
    'gnome-fs-home',
    'user-home',
  ],

  '._folder_bookmark' => [
    'user-bookmarks',
  ],

  '._desktop' => [
    'desktop',
    'gnome-fs-desktop',
    'user-desktop',
  ],

  '._network_workgroup' => [
    'gnome-fs-network',
    'gnome-mime-x-directory-smb-workgroup',
    'gtk-network',
    'network-workgroup',
    'network_local',
  ],

  '._trash_empty' => [
    'emptytrash',
    'gnome-fs-trash-empty',
    'gnome-stock-trash',
    'trashcan_empty',
    'user-trash',
    'xfce-trash_empty',
  ],

  '._trash_full' => [
    'edittrash',
    'gnome-fs-trash-full',
    'gnome-stock-trash-full',
    'stock_trash_full',
    'trashcan_full',
    'user-trash-full',
    'xfce-trash_full',
  ],
}


status_16x16 = {

  '._folder_accept' => [
    'folder-drag-accept',
    'gnome-fs-directory-accept',
  ],

  '._folder_open' => [
    'folder-open',
    'folder_open',
    'stock_open',
  ],

  '._audio_volume_low' => [
    'audio-volume-low',
    'stock_volume-0',
    'stock_volume-min',
  ],

  '._audio_volume_medium' => [
    'audio-volume-medium',
    'stock_volume-med',
  ],

  '._audio_volume_high' => [
    'audio-volume-high',
    'stock_volume-max',
    'stock_volume',
  ],

  '._audio_volume_muted' => [
    'audio-volume-muted',
    'stock_volume-mute',
  ],

  '._media_repeat' => [
    'media-playlist-repeat',
    'stock_repeat',
  ],

  '._media_shuffle' => [
    'media-playlist-shuffle',
    'stock_shuffle',
  ],

  '._msg_info' => [
    'dialog-information',
    'gtk-dialog-info',
    'info',
    'messagebox_info',
    'stock_dialog-info',
  ],

  '._msg_warning' => [
    'dialog-warning',
    'gtk-dialog-warning',
    'important',
    'messagebox_warning',
    'stock_dialog-warning',
  ],

  '._network_idle' => [
    'connect_established',
    'gnome-netstatus-idle',
    'network-idle',
    'nm-adhoc',
    'nm-device-wired',
    'nm-device-wireless',
  ],

  '._attr_key' => [
    'dialog-password',
    'gtk-dialog-authentication',
  ],
}


## 32x32
mimetypes_32x32 = {
  '._file_torrent' => [
    'application-x-bittorrent',
  ],

  '._doc_txt' => [
    'ascii',
    'empty',
    'gnome-mime-text',
    'mime_ascii',
    'misc',
    'package_editors',
    'template_source',
    'text-x-generic-template',
    'text-x-generic',
    'txt',
    'unknown',
  ],

  '._doc_pdf' => [
    'application-pdf',
    'application-x-pdf',
    'gnome-mime-application-pdf',
  ],

  '._doc_epub' => [
    'application-epub+zip',
  ],

  '._doc_fb2' => [
    'application-x-fictionbook+xml',
  ],

  '._pkg' => [
    'application-x-compressed-tar',
    'application-x-tar',
    'application-zip',
    'gnome-mime-application-x-archive',
    'gnome-mime-application-x-bzip-compressed-tar',
    'gnome-mime-application-x-bzip',
    'gnome-mime-application-x-compress',
    'gnome-mime-application-x-rar',
    'gnome-mime-application-zip',
    'gnome-package',
    'package-x-generic',
    'package',
    'zip',
    'application-x-7z-compressed',
  ],
}


## GROUP BY SIZE
size_16x16 = {
  'actions' => actions_16x16,
  'apps' => apps_16x16,
  'categories' => categories_16x16,
  'devices' => devices_16x16,
  'mimetypes' => mimetypes_16x16,
  'places' => places_16x16,
  'status' => status_16x16,
}


size_32x32 = {
  'mimetypes' => mimetypes_32x32,
}


## THEME
theme = {
  '16x16' => size_16x16,
  '32x32' => size_32x32,
}


def check_dir(dir)
  unless File.directory?(dir)
    Dir.mkdir(dir)
  end
end


def run(theme)
  theme_root = File.expand_path("../#{THEME_NAME}")
  errors = []

  check_dir(theme_root)

  theme.each do |size, size_in|
    dir_out = File.join(theme_root, size)
    check_dir(dir_out)

    ext = size[/^scalable/] ? ".svg" : ".png"

    size_in.each do |cat, cat_in|
      dir_out =File.join(theme_root, size, cat)
      check_dir(dir_out)
      Dir.chdir(dir_out)

      puts cat

      cat_in.each do |name, links|
        name = "#{name}#{ext}"

        unless File.exist?(name)
          error_string = "!!! ERROR - File not found ---> \"#{name}\""
          #error_string = "!!! ERROR - File not found ---> \"#{name}\""
          puts error_string
          errors << error_string
          next
        end

        links.each do |link|
          link = "#{link}#{ext}"

          puts_string = "\"#{name}\" <--- \"#{link}\""

          if File.symlink?(link)
            puts "SKIPPED - " + puts_string
            next
          end

          unless File.symlink(name, link)
            error_string = "!!! ERROR - Unable to create link ---> " + puts_string
            puts error_string
            errors << error_string
            next
          end

          puts "OK - " + puts_string
        end

        puts
      end
    end
  end

  puts "\nERRORS - #{errors.size}\n" if errors.size > 0
end


run(theme)

